
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./components/Providers";
import React from 'react';
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <CartProvider>{children}</CartProvider>

        </Providers>
      </body>
    </html>
  );
}
